server:
  port: 10100

mybatis:
  config-location: classpath:mybatis.cfg.xml
  type-aliases-package: com.example.backend.entity
  mapper-locations:
    - classpath:mapper/*.xml


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/online_study?serverTimezone=GMT%2B8&useSSL=FALSE&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      field-strategy: IGNORED
      #
      db-type: MYSQL
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
